# -*- coding: utf-8 -*-
"""carpeta para visual studio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SCWssJTOOMq15UVT6-vjZaFGsRYFyWD
"""

import os

def suma(a, b):
    resultado = a + b
    return resultado

def resta(a, b):
    resultado = a - b
    return resultado

def division(a, b):
    resultado = a / b
    return resultado

def multiplicacion(a, b):
    resultado = a * b
    return resultado

def burbuja(lista):
    for _ in range(len(lista)):
        for j in range(len(lista) - 1):
            if lista[j] > lista[j+1]:
                lista[j], lista[j+1] = lista[j+1], lista[j]

def burbuja(lista):
    for _ in range(len(lista)):
        for j in range(len(lista) - 1):
            if lista[j] < lista[j+1]:
                lista[j], lista[j+1] = lista[j+1], lista[j]

def suma(a, b):
    return a + b

def resta(a, b):
    return a - b

def multiplicacion(a, b):
    return a * b

def division(a, b):
    return a / b

def crear_carpeta():
    while True:
        print("Elegi una opción: suma, resta, división, multiplicación, ordenar_asc, ordenar_desc, salir")
        opcion = input("Selecciona una opción: ")

        if opcion == "salir":
            print("¡Adiós!")
            break
        elif opcion in ["suma", "resta", "multiplicacion", "division"]:
            num1 = int(input("Selecciona un número: "))
            num2 = int(input("Selecciona otro número: "))

            if opcion == "suma":
                print("El resultado de la suma es:", suma(num1, num2))
            elif opcion == "resta":
                print("El resultado de la resta es:", resta(num1, num2))
            elif opcion == "multiplicacion":
                print("El resultado de la multiplicación es:", multiplicacion(num1, num2))
            elif opcion == "division":
                if num2 == 0:
                    print("No se puede dividir por cero.")
                else:
                    print("El resultado de la división es:", division(num1, num2))
        elif opcion == "ordenar_asc":
            list3 = ["Bruno", "Joaquin", "Martin", "Gonzalo", "Franco", "Matias", "Quimy", "Marti"]
            burbuja(list3)
            print("Lista ordenada alfabéticamente (sin modificar la lista original):", list3)
        elif opcion == "ordenar_desc":
            list3 = ["Bruno", "Joaquin", "Martin", "Gonzalo", "Franco", "Matias", "Quimy", "Marti"]
            burbuja(list3)
            print("Lista ordenada alfabéticamente en orden descendente (sin modificar la lista original):", list3)
        else:
            print("Opción no válida. Por favor, selecciona una opción válida.")

crear_carpeta()
